theme: jekyll-theme-primer
title: World Cup 2018 Predictions
description: Analysis and predictions
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
